[package]
name = "json-to-mse"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
derive_more = "*"
zip = "*"

[target.'cfg(not(windows))'.dependencies]
termion = "1"

[dependencies.mtg]
git = "https://github.com/fenhl/rust-mtg"
