[package]
name = "json-to-mse"
version = "2.0.0-alpha.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
css-color-parser = "0"
derive_more = "0"
dirs = "2"
itertools = "0"
reqwest = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
shlex = "0"
zip = "0"

[target.'cfg(not(windows))'.dependencies]
termion = "1"

[dependencies.gitdir]
git = "https://github.com/fenhl/rust-gitdir"

[dependencies.mtg]
git = "https://github.com/fenhl/rust-mtg"

[dependencies.url]
version = "2"
features = ["serde"]
